version: '2'
services:
    lotmicro-postgresql:
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/lotmicro/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=lotmicro
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
